name: 버그 리포트
description: 발견한 버그를 보고해주세요
title: '[Bug] '
labels: [bug]
body:
  - type: textarea
    id: what-happened
    attributes:
      label: 어떤 문제가 발생했나요?
      description: 버그에 대한 설명을 최대한 자세히 작성해주세요.
      placeholder: 예) 로그인 시 페이지가 하얗게 멈춤
    validations:
      required: true

  - type: textarea
    id: expected
    attributes:
      label: 기대한 동작
      description: 원래 기대했던 정상 동작은 무엇인가요?
    validations:
      required: true

  - type: textarea
    id: reproduce
    attributes:
      label: 재현 방법
      description: 버그를 재현하기 위한 단계 (가능한 경우)
      placeholder: |
        1. 로그인 페이지로 이동
        2. 이메일/비밀번호 입력
        3. 로그인 버튼 클릭
        4. 페이지 멈춤
    validations:
      required: false

  - type: dropdown
    id: environment
    attributes:
      label: 환경 정보
      description: 문제가 발생한 환경을 선택해주세요
      options:
        - Windows (Chrome)
        - macOS (Safari)
        - iOS (Safari)
        - Android (Chrome)
        - 기타
    validations:
      required: false
