name: 질문 또는 기타 이슈
description: 질문, 토론 또는 일반 이슈를 등록합니다
title: '[Discussion] '
labels: [question]
body:
  - type: textarea
    id: context
    attributes:
      label: 내용
      description: 논의하고 싶은 주제나 질문을 자세히 설명해주세요.
    validations:
      required: true

  - type: textarea
    id: expected-result
    attributes:
      label: 기대하는 결과
      description: 해결되었을 때 어떤 결과를 기대하나요?
    validations:
      required: false
